a = input('Digite algo: ')
print('A classe dessa variavel é:\n', type(a))
print('É formado só por espaços ?\n', a.isspace())
print('É formado por numeros ?\n', a.isalnum())
print('É alfabetico ?\n', a.isalpha())
print('É alfanumerico ?\n', a.isalnum())
print('Está em maiúsculo ?\n', a.isupper())
print('Está em minusculo ?\n', a.islower())
print('Está capitalizada ?\n', a.istitle())
